trigger:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb O ALGO ASI"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - bash: |
      echo ">>> Compile vscode-test"
      yarn && yarn compile
      echo ">>> Compiled vscode-test"
      cd sample
      echo ">>> Run sample integration test"
      yarn && yarn compile && yarn test
    displayName: Run Tests
    env:
      DISPLAY: ":99.0"

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: "SonarCloud"
      organization: "zerasul-github"
      scannerMode: "CLI"
      configMode: "manual"
      cliProjectKey: "genesis-code-project"
      cliProjectName: "Genesis Code"
      cliSources: "src/"
      extraProperties: |
        # Additional properties that will be passed to the scanner, 
        # Put one key=value per line, example:
        sonar.exclusions=src/test/

  - task: SonarCloudAnalyze@1
